spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
stripe:
  apiUrl: https://api.stripe.com/v1
  enabled: true
  timeout: 1000
  currencies: USD,EUR,GBP
payment-gateway: paypal
mail:
  host: https://smtp.gmail.com
  port: 576